### ISSUE TITLE
Fantastic idea 👍

### ISSUE THREAD

**Issue by SimplGy** [alangrainger/obsidian-air-quotes#1]
Just wanted to say, as someone who also reads on kindle, has tried Readwise and some other alternatives...

This is a great idea. 🥂

I'm glad you thought of it and it looks like it works really smoothly. Can't wait for it to hit the plugin store.

(neat product name, too)

(feel free to close this issue, of course)

**Comment by ArtemisFowl-san** [comment]
Just wanted to agree with the statement above. This really helped me with writing a review for a dense book I was reading for university :)

**Comment by alangrainger** [comment]
Thanks both! And especially @ArtemisFowl-san, it's really cool to know it's actually useful for people other than me.

**Comment by Domi923** [comment]
Also wanted to say thank you for this awesome plugin!

One question, though, how do you put a kindle eBook into markdown? Haven't found a way to put a whole kindle book (bought on Amazon) into a markdown file.

**Comment by alangrainger** [comment]
> One question, though, how do you put a kindle eBook into markdown? Haven't found a way to put a whole kindle book (bought on Amazon) into a markdown file.

1. Remove the DRM with Apprentice Alf’s DeDRM tool.
2. Convert to ePub using Calibre.
3. Convert to Markdown using Pandoc.

I can't give any more detailed steps sorry, but there are tons of tutorials around showing you how to do this.

**Comment by alangrainger** [comment]
@SimplGy this is now in the plugin store:

https://obsidian.md/plugins?id=air-quotes
