### ISSUE TITLE
extract images

### ISSUE THREAD

**Issue by lbgws2** [alangrainger/obsidian-air-quotes#2]
i just use the plugin import epub file,it works well

is there any way extract images ?

**Comment by alangrainger** [comment]
That's not on the roadmap for implementing, sorry to say. The purpose for the epub import is to get the _source text_ into your vault, for the purpose of extracting quotes.

In terms of extracting text quotes, bringing in the images also would drastically increase the size of the vault for no reason.

If someone wants to code it up with a setting to turn images on/off, I'll have a look at the Pull Request.

**Comment by lbgws2** [comment]
i want use this plugin to read about Reading technical books usually comes with many images, which are very helpful for understanding the content


So I suggest setting the option 'setting to turn images on/off' to allow users to choose for themselves

**Comment by alangrainger** [comment]
There are already some great options for getting a Markdown copy of a book into your vault, including all images. Have you tried Pandoc or Calibre? They're no need for me to reinvent the wheel - there are already excellent options out there 👍
